# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a13e83b99844757eac0494a2b628debd1ec0419f50f3ed6494e18bb4a6820f43c00915e82acb8a89db7570057793430ceeaa66e9672fc9bebe19a8651748b8d2

test:
  secret_key_base: aeb0d075be0206c1ed381edc9fceac5eec1496088c33113e722c17cfc5557a57fcc9dc7fdbd8b7a1b26d70a403f0440bff12c942be3d6385e66805a35f8f94ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
